### ISSUE TITLE
Can't download images, former site gone?

### ISSUE THREAD

**Issue by Sothanforax** [jamessanford/kegs#6]
The app sits and spins on "Preparing disk image..." forever, and https://jsan.co/KEGS/images no longer leads to anything
if possible put up the images on your new site, a github page, or perhaps just bundle the images within an apk.

**Comment by jamessanford** [comment]
Thanks!  `jsan.co` should be back online.  The old APK should be able to get the ROM file now.

The old APK had two images baked into it (X-MAS Demo and System 6 from https://www.whatisthe2gs.apple2.org.za/home/index.html ) but relied on the external site for the ROM.

Did you build the app from source or are you using the old APK?

**Comment by jamessanford** [comment]
When building from source, the disk image assets aren't present, so in 93196b71d97eec05887dd1cf0d69fbe88699d564 I've marked them as downloadable images.

Let me know if you still have issues!

**Comment by Sothanforax** [comment]
> Thanks! `jsan.co` should be back online. The old APK should be able to get the ROM file now.
> 
> The old APK had two images baked into it (X-MAS Demo and System 6 from https://www.whatisthe2gs.apple2.org.za/home/index.html ) but relied on the external site for the ROM.
> 
> Did you build the app from source or are you using the old APK?

Ah I built from source, thanks for the quick response though!
